[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "llpvtools"
version = "0.0.1"
dependencies = [
    "landlab",
    "numpy",
    "pyvista",
]

[project.optional-dependencies]
examples = [
    "notebook",
    "pyvista[jupyter]",
]
